// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxBMnnyJiq03wOZVUiMgAfCY6FlzDLHA',
    appId: '1:144980366128:web:967ca7f728309b23bdeef5',
    messagingSenderId: '144980366128',
    projectId: 'shift-lift-31fd9',
    authDomain: 'shift-lift-31fd9.firebaseapp.com',
    storageBucket: 'shift-lift-31fd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInVJxb-ClwdcaYr4I7omzGJaEAgWXKnk',
    appId: '1:144980366128:android:54ff5df45b39e895bdeef5',
    messagingSenderId: '144980366128',
    projectId: 'shift-lift-31fd9',
    storageBucket: 'shift-lift-31fd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrIKjM1c3msEecpEa3bO8peebUgXVuiyo',
    appId: '1:144980366128:ios:cd62b718e9062db3bdeef5',
    messagingSenderId: '144980366128',
    projectId: 'shift-lift-31fd9',
    storageBucket: 'shift-lift-31fd9.appspot.com',
    androidClientId: '144980366128-0h2u3p50vokatis2fhlpcvgdiitv3jli.apps.googleusercontent.com',
    iosClientId: '144980366128-b7n7ruht5kan65pr2amhqehjk9of9j6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.shiftLift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrIKjM1c3msEecpEa3bO8peebUgXVuiyo',
    appId: '1:144980366128:ios:cd62b718e9062db3bdeef5',
    messagingSenderId: '144980366128',
    projectId: 'shift-lift-31fd9',
    storageBucket: 'shift-lift-31fd9.appspot.com',
    androidClientId: '144980366128-0h2u3p50vokatis2fhlpcvgdiitv3jli.apps.googleusercontent.com',
    iosClientId: '144980366128-b7n7ruht5kan65pr2amhqehjk9of9j6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.shiftLift',
  );
}
